publish:
  whoami: asf-site

github:
  enabled_merge_buttons:
    # enable squash button:
    squash:  true
    # disable rebase button:
    rebase:  true
    # enable merge button:
    merge:   false
