publish:
  whoami: asf-site

github:
  enabled_merge_buttons:
    # enable squash button:
    squash: true
    # disable rebase button:
    rebase: true
    # enable merge button:
    merge: false
  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
